from enum import Enum

class Platform(str, Enum):
    INSTAGRAM = "INSTAGRAM"
    FACEBOOK = "FACEBOOK"
    TWITTER_X = "TWITTER_X"
    LINKEDIN = "LINKEDIN"
    TIKTOK = "TIKTOK"

class ContentType(str, Enum):
    POST = "POST"
    STORY = "STORY"
    REEL = "REEL"
    CAROUSEL = "CAROUSEL"
    THREAD = "THREAD"
    AD = "AD"

class ContentPillarType(str, Enum):
    EDUCATIONAL = "EDUCATIONAL"
    ENTERTAINING = "ENTERTAINING"
    PROMOTIONAL = "PROMOTIONAL"
    BEHIND_THE_SCENES = "BEHIND_THE_SCENES"
    USER_GENERATED = "USER_GENERATED"
    THOUGHT_LEADERSHIP = "THOUGHT_LEADERSHIP"

class CampaignObjectiveType(str, Enum):
    AWARENESS = "AWARENESS"
    CONSIDERATION = "CONSIDERATION"
    CONVERSION = "CONVERSION"
    ENGAGEMENT = "ENGAGEMENT"
    RETENTION = "RETENTION"

class AdStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class Tone(str, Enum):
    PROFESSIONAL = "PROFESSIONAL"
    CASUAL = "CASUAL"
    HUMOROUS = "HUMOROUS"
    AUTHORITATIVE = "AUTHORITATIVE"
    EMPATHETIC = "EMPATHETIC"
    INSPIRATIONAL = "INSPIRATIONAL"

class PostStatus(str, Enum):
    DRAFT = "DRAFT"
    REVIEW = "REVIEW"
    SCHEDULED = "SCHEDULED"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
